/*
 * Created by victoria on 16.02.20.
*/
#pragma once

enum http_status
{
	HTTP_S_OK = 200,

	HTTP_S_BAD_REQUEST = 400,
	HTTP_S_UNAUTHORIZED = 401,
	HTTP_S_FORBIDDEN = 403,
	HTTP_S_NOT_FOUND = 404,
	HTTP_S_METHOD_NOT_ALLOWED = 405,
	HTTP_S_NOT_ACCEPTABLE = 406,
	HTTP_S_REQUEST_TIMEOUT = 408,
	HTTP_S_LENGTH_REQUIRED = 411,
	HTTP_S_PAYLOAD_TOO_LARGE = 413,
	HTTP_S_URI_TOO_LONG = 414,
	HTTP_S_UNSUPPORTED_MEDIA_TYPE = 415,
	HTTP_S_EXPECTATION_FAILED = 417,
	HTTP_S_HEADER_TOO_LARGE = 431,

	HTTP_S_SERVER_ERROR = 500,
	HTTP_S_NOT_IMPLEMENTED = 501,
	HTTP_S_BAD_GATEWAY = 502,
	HTTP_S_SERVICE_UNAVAILABLE = 503,
	HTTP_S_GATEWAY_TIMEOUT = 504,
	HTTP_S_VERSION_NOT_SUPPORTED = 505
};

const char *
status_message(enum http_status status);
