name: CMake CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@master
      - name: configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: build
        run: |
          cd build
          make
      - name: test request
        run: |
          test/test.sh
