name: CMake CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: configure
        run: |
          mkdir build
          cd build
          cmake ..
      - name: build
        run: make
      - name: test request
        run: |
          cd ..
          test/test.sh
